# Generated by ChatGPT on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="escrowtransaction",
            name="payout_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payout_status",
            field=models.CharField(blank=True, default="PENDING", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payaza_payment_check_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payaza_payout_check_response",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payaza_last_payment_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="escrowtransaction",
            name="payaza_last_payout_check",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

