# Generated by Django 6.0.4 on 2026-05-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_add_payaza_payout_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completion_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="escrowtransaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Payment Pending"),
                    ("HELD", "Held in Escrow"),
                    ("RELEASED", "Released to Worker"),
                    ("REFUNDED", "Refunded to Poster"),
                    ("DISPUTED", "In Dispute"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
